spring:
    datasource:
        name: test
        url: jdbc:mysql://10.7.19.165:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Exam12.21
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    mapper-locations: classpath:mapping/user-mapper.xml
    #type-aliases-package: com.db1.pojo
    config-location: classpath:mybatis/mybatis-config.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

